// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1, arg2) {
  return window['go']['controllers']['AccountController']['DeleteAccount'](arg1, arg2);
}

export function DeleteUserAccount(arg1, arg2) {
  return window['go']['controllers']['AccountController']['DeleteUserAccount'](arg1, arg2);
}

export function GetUserList(arg1, arg2) {
  return window['go']['controllers']['AccountController']['GetUserList'](arg1, arg2);
}

export function ResetUserPassword(arg1) {
  return window['go']['controllers']['AccountController']['ResetUserPassword'](arg1);
}

export function UpdateName(arg1, arg2, arg3) {
  return window['go']['controllers']['AccountController']['UpdateName'](arg1, arg2, arg3);
}

export function UpdatePassword(arg1, arg2, arg3) {
  return window['go']['controllers']['AccountController']['UpdatePassword'](arg1, arg2, arg3);
}
