// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteAccount(arg1:string,arg2:number):Promise<string>;

export function DeleteUserAccount(arg1:number,arg2:number):Promise<string>;

export function GetUserList(arg1:number,arg2:number):Promise<string>;

export function ResetUserPassword(arg1:number):Promise<string>;

export function UpdateName(arg1:string,arg2:string,arg3:number):Promise<string>;

export function UpdatePassword(arg1:string,arg2:string,arg3:number):Promise<string>;
