// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentUser(arg1) {
  return window['go']['controllers']['AuthController']['GetCurrentUser'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['controllers']['AuthController']['Login'](arg1, arg2);
}

export function Register(arg1, arg2, arg3) {
  return window['go']['controllers']['AuthController']['Register'](arg1, arg2, arg3);
}
