// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateElderly(arg1) {
  return window['go']['controllers']['DataController']['CreateElderly'](arg1);
}

export function DeleteElderly(arg1) {
  return window['go']['controllers']['DataController']['DeleteElderly'](arg1);
}

export function GetElderly(arg1) {
  return window['go']['controllers']['DataController']['GetElderly'](arg1);
}

export function GetElderlyList(arg1, arg2, arg3) {
  return window['go']['controllers']['DataController']['GetElderlyList'](arg1, arg2, arg3);
}

export function GetMyElderlyList(arg1, arg2, arg3, arg4) {
  return window['go']['controllers']['DataController']['GetMyElderlyList'](arg1, arg2, arg3, arg4);
}

export function GetSummary() {
  return window['go']['controllers']['DataController']['GetSummary']();
}

export function UpdateElderly(arg1, arg2) {
  return window['go']['controllers']['DataController']['UpdateElderly'](arg1, arg2);
}
