// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseIssue(arg1:number):Promise<string>;

export function CreateIssue(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<string>;

export function DeleteIssue(arg1:number):Promise<string>;

export function GetIssue(arg1:number):Promise<string>;

export function GetIssueList(arg1:number,arg2:number,arg3:string):Promise<string>;

export function RespondToIssue(arg1:number,arg2:string,arg3:number):Promise<string>;

export function UpdateIssueStatus(arg1:number,arg2:string):Promise<string>;
