// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseIssue(arg1) {
  return window['go']['controllers']['IssueController']['CloseIssue'](arg1);
}

export function CreateIssue(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['controllers']['IssueController']['CreateIssue'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteIssue(arg1) {
  return window['go']['controllers']['IssueController']['DeleteIssue'](arg1);
}

export function GetIssue(arg1) {
  return window['go']['controllers']['IssueController']['GetIssue'](arg1);
}

export function GetIssueList(arg1, arg2, arg3) {
  return window['go']['controllers']['IssueController']['GetIssueList'](arg1, arg2, arg3);
}

export function RespondToIssue(arg1, arg2, arg3) {
  return window['go']['controllers']['IssueController']['RespondToIssue'](arg1, arg2, arg3);
}

export function UpdateIssueStatus(arg1, arg2) {
  return window['go']['controllers']['IssueController']['UpdateIssueStatus'](arg1, arg2);
}
