// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSurvey(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['controllers']['SurveyController']['CreateSurvey'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DeleteSurvey(arg1) {
  return window['go']['controllers']['SurveyController']['DeleteSurvey'](arg1);
}

export function GetActiveSurveys() {
  return window['go']['controllers']['SurveyController']['GetActiveSurveys']();
}

export function GetSurvey(arg1) {
  return window['go']['controllers']['SurveyController']['GetSurvey'](arg1);
}

export function GetSurveyList(arg1, arg2) {
  return window['go']['controllers']['SurveyController']['GetSurveyList'](arg1, arg2);
}

export function GetSurveyResults(arg1) {
  return window['go']['controllers']['SurveyController']['GetSurveyResults'](arg1);
}

export function UpdateSurveyStatus(arg1, arg2) {
  return window['go']['controllers']['SurveyController']['UpdateSurveyStatus'](arg1, arg2);
}

export function Vote(arg1, arg2, arg3) {
  return window['go']['controllers']['SurveyController']['Vote'](arg1, arg2, arg3);
}
