// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateSurvey(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<string>;

export function DeleteSurvey(arg1:number):Promise<string>;

export function GetActiveSurveys():Promise<string>;

export function GetSurvey(arg1:number):Promise<string>;

export function GetSurveyList(arg1:number,arg2:number):Promise<string>;

export function GetSurveyResults(arg1:number):Promise<string>;

export function UpdateSurveyStatus(arg1:number,arg2:string):Promise<string>;

export function Vote(arg1:number,arg2:string,arg3:number):Promise<string>;
